apiVersion: v1
kind: Service
metadata:
  name: django-svc
  namespace: node-todo-app
spec:
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  type: LoadBalancer
  selector:
       app: django-todo-deployment
