apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  ports:
  - port: 8090
    nodePort: 30001
    targetPort: java-app-container
    protocol: http
  selector: 
       app: java-app
  type: NodePort

