- name: this playbook will install httpd
  hosts: db01
  become: yes 
  tasks:
    - name: Install httpd
      apt:
        name: httpd
        state: present
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
    - name: Install MySQL server
      apt:
        name: mariadb-server
        state: present
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

